### ISSUE TITLE
korean

### ISSUE THREAD

**Issue by tycoomw1** [Nomi-CEu/Nomi-CEu-Translations#23]
Please add Korean.

**Comment by marisathewitch** [comment]
Good evening. 
Unfortunately, at the moment, there are no members in our team who speak Korean. However, if you know the language and would like to assist with the translation of the Nomifactory modpack into Korean, you can use Weblate.
Link is available in Discord channel and in description for repository. 
Thank you.

**Comment by IntegerLimit** [comment]
This is done in Nomi-CEu-Translations. Closing.
